Fix receiver name in client and pretty code
vmware/go-vcloud-director pull request #379
Opened 2021-05-28 10:40 UTC by crashiura

This was a trivial fix so there is no related Issue
I added comments and fixed receiver name in client.

2021-05-28 12:00 UTC, Didainius reviewed
Thanks for this PR.

Just a question - did you run  any test on it. I saw there were a few shuffles on error handling and wondering if it has any consequences.

2021-05-28 12:00 UTC, Didainius commented on govcd/admincatalog.go
> +// UploadOvf Uploads an ova file to a catalog. This method only uploads bits to vCD spool area.
```suggestion
// UploadOvf uploads an ova file to a catalog. This method only uploads bits to vCD spool area.
```

2021-05-28 12:00 UTC, Didainius commented on govcd/api.go
> +// IsNotFound Convenience function, similar to os.IsNotExist that checks whether a given error
```suggestion
// IsNotFound is a convenience function, similar to os.IsNotExist that checks whether a given error
```

2021-05-28 12:00 UTC, Didainius commented on govcd/api.go
> +// ExecuteTaskRequest Helper function creates request, runs it, checks response and parses task from response.
```suggestion
// ExecuteTaskRequest helper function creates request, runs it, checks response and parses task from response.
```

2021-05-28 12:00 UTC, Didainius commented on govcd/api.go
> +// ExecuteTaskRequestWithApiVersion Helper function creates request, runs it, checks response and parses task from response.
```suggestion
// ExecuteTaskRequestWithApiVersion helper function creates request, runs it, checks response and parses task from response.
```

2021-05-28 12:00 UTC, Didainius commented on govcd/api.go
> +// ExecuteRequestWithoutResponse Helper function creates request, runs it, checks response and do not expect any values from it.
```suggestion
// ExecuteRequestWithoutResponse helper function creates request, runs it, checks response and do not expect any values from it.
```

2021-05-28 12:00 UTC, Didainius commented on govcd/api.go
> +// ExecuteRequestWithoutResponseWithApiVersion Helper function creates request, runs it, checks response and do not expect any values from it.
```suggestion
// ExecuteRequestWithoutResponseWithApiVersion helper function creates request, runs it, checks response and do not expect any values from it.
```

2021-05-28 12:00 UTC, Didainius commented on govcd/api.go
> +// ExecuteRequest Helper function creates request, runs it, check responses and parses out interface from response.
```suggestion
// ExecuteRequest helper function creates request, runs it, check responses and parses out interface from response.
```

2021-05-28 12:00 UTC, Didainius commented on govcd/api.go
> +// ExecuteRequestWithApiVersion Helper function creates request, runs it, check responses and parses out interface from response.
```suggestion
// ExecuteRequestWithApiVersion helper function creates request, runs it, check responses and parses out interface from response.
```

2021-05-28 12:00 UTC, Didainius commented on govcd/api.go
> +		return nil, fmt.Errorf("could parse path requestURI %s", err)
```suggestion
		return nil, fmt.Errorf("could parse path request URI '%s': %s", pathURL, err)
```

2021-05-28 12:00 UTC, Didainius commented on govcd/vm.go
> +// NewVMRecord create instance with reference to types.QueryResultVMRecordType
```suggestion
// NewVMRecord creates an instance with reference to types.QueryResultVMRecordType
```

2021-05-28 12:00 UTC, Didainius commented on govcd/vm.go
> +// ChangeCPUCount Sets number of available virtual logical processors
```suggestion
// ChangeCPUCount sets number of available virtual logical processors
```

2021-05-28 12:00 UTC, Didainius commented on govcd/vm.go
> +// ChangeCPUCountWithCore Sets number of available virtual logical processors
```suggestion
// ChangeCPUCountWithCore sets number of available virtual logical processors
```

2021-05-28 12:00 UTC, Didainius commented on govcd/vm.go
> +// AttachDisk Attach an independent disk
```suggestion
// AttachDisk attaches an independent disk
```

2021-05-28 12:00 UTC, Didainius commented on govcd/vm.go
> +// DetachDisk Detach an independent disk
```suggestion
// DetachDisk detaches an independent disk
```

2021-05-28 12:00 UTC, Didainius commented on govcd/vm.go
> +// HandleInsertMedia Helper function which finds media and calls InsertMedia
```suggestion
// HandleInsertMedia helper function finds media and calls InsertMedia
```

2021-05-28 12:00 UTC, Didainius commented on govcd/vm.go
> +// HandleEjectMedia Helper function which finds media and calls EjectMedia
```suggestion
// HandleEjectMedia is a helper function which finds media and calls EjectMedia
```

2021-05-28 12:00 UTC, Didainius commented on govcd/vm.go
> +// InsertMedia Insert media for VM
```suggestion
// InsertMedia inserts media for a VM
```

2021-05-28 12:00 UTC, Didainius commented on govcd/vm.go
> +// EjectMedia Eject media from VM
```suggestion
// EjectMedia ejects media from VM
```

2021-05-28 12:00 UTC, Didainius commented on govcd/vm.go
> +// AnswerQuestion Use the provide answer to existing VM question for operation which need additional response
```suggestion
// AnswerQuestion uses the provided answer to existing VM question for operation which need additional response
```

2021-05-28 12:00 UTC, Didainius commented on govcd/vm.go
> +// GetQuestion Use the get existing VM question for operation which need additional response
```suggestion
// GetQuestion uses the get existing VM question for operation which need additional response
```

2021-05-28 22:02 UTC, crashiura commented
Thank you for comments, I ran unit tests

2021-05-30 18:27 UTC, Didainius approved these changes
Looks like it does not impacts tests after run.
Thanks.

Also - please do add a comment to `CHANGELOG.md` before other team members review it.

2021-05-31 09:18 UTC, crashiura commented
I added comment in changelog.

2021-06-02 07:34 UTC, lvirbalas commented on CHANGELOG.md
> +* Improved error handling and fix receiver name in client
```suggestion
* Improved error handling and function receiver name in client
```

2021-06-02 12:27 UTC, lvirbalas approved these changes
LGTM, thanks for contributing.

2021-06-15 12:35 UTC, crashiura commented
@dataclouder check pls

2021-06-17 07:12 UTC, dataclouder requested changes

2021-06-17 07:12 UTC, dataclouder commented on govcd/api.go
> +		return nil, fmt.Errorf("could parse path request URI '%s': %s", pathURL, err)
```suggestion
		return nil, fmt.Errorf("couldn't parse path request URI '%s': %s", pathURL, err)
```

2021-06-17 07:12 UTC, dataclouder commented on govcd/vm.go
> +		return types.VmPendingQuestion{}, fmt.Errorf("error getting question: %s", err)
```suggestion
		return types.VmPendingQuestion{}, fmt.Errorf("error getting VM question: %s", err)
```

2021-06-22 11:03 UTC, crashiura commented
@dataclouder done

2021-07-28 20:05 UTC, crashiura commented
@dataclouder Hi, check pls

2021-09-08 11:54 UTC, dataclouder approved these changes

2021-10-06 07:25 UTC, merged