Improve RDE related methods
vmware/go-vcloud-director pull request #615
Opened 2023-09-08 10:56 UTC by adambarreiro

This PR modifies the following:

- Makes `DefinedEntityType.SetBehaviorAccessControls` more robust to avoid NullPointerException errors in VCD side when the input is a nil slice.

2023-09-12 14:31 UTC, lvirbalas approved these changes

2023-09-26 09:14 UTC, adezxc approved these changes

2023-10-02 13:23 UTC, dataclouder requested changes
Can we add a test to demonstrate the assumption? i.e. getting an array of nil as input

2023-10-02 14:58 UTC, dataclouder approved these changes

2023-10-05 07:53 UTC, Didainius approved these changes

2023-10-05 07:55 UTC, merged